<?php
// This script and data application were generated by AppGini 23.16
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('Donations');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'SupporterID':
			if(!$id) {
				?>
				$j('#MailingName<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Address1<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Address2<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#City<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#State<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Zip<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Country<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `Supporters`.`ID` as 'ID', `Supporters`.`FirstName` as 'FirstName', `Supporters`.`LastName` as 'LastName', `Supporters`.`SpouseName` as 'SpouseName', `Supporters`.`Address1` as 'Address1', `Supporters`.`Address2` as 'Address2', `Supporters`.`City` as 'City', `Supporters`.`State` as 'State', `Supporters`.`Zip` as 'Zip', if(CHAR_LENGTH(`Supporters`.`Country`)>20, concat(left(`Supporters`.`Country`,20),' ...'), `Supporters`.`Country`) as 'Country', CONCAT_WS('-', LEFT(`Supporters`.`Phone`,3), MID(`Supporters`.`Phone`,4,3), RIGHT(`Supporters`.`Phone`,4)) as 'Phone', CONCAT_WS('-', LEFT(`Supporters`.`Cell`,3), MID(`Supporters`.`Cell`,4,3), RIGHT(`Supporters`.`Cell`,4)) as 'Cell', `Supporters`.`Email` as 'Email', `Supporters`.`Status` as 'Status', `Supporters`.`ContactMethod` as 'ContactMethod', `Supporters`.`TotalDonated` as 'TotalDonated', `Supporters`.`TotalMatched` as 'TotalMatched', `Supporters`.`MailingName` as 'MailingName', `Supporters`.`MailingNameFull` as 'MailingNameFull' FROM `Supporters`  WHERE `Supporters`.`ID`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#MailingName<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['MailingNameFull']))); ?>&nbsp;');
			$j('#Address1<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Address1']))); ?>&nbsp;');
			$j('#Address2<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Address2']))); ?>&nbsp;');
			$j('#City<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['City']))); ?>&nbsp;');
			$j('#State<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['State']))); ?>&nbsp;');
			$j('#Zip<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Zip']))); ?>&nbsp;');
			$j('#Country<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Country']))); ?>&nbsp;');
			<?php
			break;


	}

?>